name: 'Build and Push Docker Image'
description: 'Builds and pushes Docker image to GitHub Container Registry'
inputs:
  docker-file:
    description: 'Path to the Dockerfile'
    required: false
    default: './Dockerfile'
  image-name:
    description: 'Name of the Docker image to build and push'
    required: true
  image-tag:
    description: 'Tag for the Docker image'
    required: true
  image-platform:
    description: 'Target platform for the Docker image'
    required: false
    default: 'linux/amd64'
  build-args:
    description: 'Build arguments for Docker build'
    required: false
    default: ''
  github-token:
    description: 'GitHub token for registry authentication'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ inputs.github-token }}

    - name: Prepare Docker build args
      id: prepare_build_args
      shell: bash
      run: |
        # Convert space-separated to newline-separated
        args="${{ inputs.build-args }}"
        build_args=$(echo "$args" | tr ' ' '\n')
        {
          echo "build_args<<EOF"
          echo "$build_args"
          echo "EOF"
        } >> "$GITHUB_OUTPUT"

    - name: Build and push container image to registry
      uses: docker/build-push-action@v5
      with:
          context: .
          push: true
          tags: ${{ inputs.image-name }}:${{ inputs.image-tag }}
          file: ${{ inputs.docker-file }}
          platforms: ${{ inputs.image-platform }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: ${{ steps.prepare_build_args.outputs.build_args }}
