name: 'Run Code Generation'
description: 'Runs various code generation tasks (GraphQL, PayloadCMS, etc.)'
inputs:
  generate-importmap:
    description: 'Run importmap generation'
    required: false
    default: 'true'
  generate-types:
    description: 'Run type generation'
    required: false
    default: 'true'
  generate-graphql:
    description: 'Run GraphQL code generation'
    required: false
    default: 'false'
  generate-payload:
    description: 'Run PayloadCMS type generation'
    required: false
    default: 'false'
  custom-commands:
    description: 'Additional custom generation commands (space-separated)'
    required: false
    default: ''
  custom-command:
    description: 'Single custom command to run instead of all standard commands'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Run Custom Command
      if: inputs.custom-command != ''
      shell: bash
      run: |
        echo "🔄 Running custom command: ${{ inputs.custom-command }}"
        ${{ inputs.custom-command }}
        echo "✅ Custom command completed"

    - name: Generate ImportMap
      if: inputs.custom-command == '' && inputs.generate-importmap == 'true'
      shell: bash
      run: |
        if pnpm run --silent generate:importmap 2>/dev/null; then
          echo "✅ ImportMap generation completed"
        else
          echo "⚠️ ImportMap generation script not found, skipping"
        fi

    - name: Generate Types
      if: inputs.custom-command == '' && inputs.generate-types == 'true'
      shell: bash
      run: |
        if pnpm run --silent generate:types 2>/dev/null; then
          echo "✅ Type generation completed"
        else
          echo "⚠️ Type generation script not found, skipping"
        fi

    - name: Generate GraphQL
      if: inputs.custom-command == '' && inputs.generate-graphql == 'true'
      shell: bash
      run: |
        if pnpm run --silent generate:graphql 2>/dev/null; then
          echo "✅ GraphQL generation completed"
        else
          echo "⚠️ GraphQL generation script not found, skipping"
        fi

    - name: Generate PayloadCMS Types
      if: inputs.custom-command == '' && inputs.generate-payload == 'true'
      shell: bash
      run: |
        if pnpm run --silent generate:payload 2>/dev/null; then
          echo "✅ PayloadCMS generation completed"
        else
          echo "⚠️ PayloadCMS generation script not found, skipping"
        fi

    - name: Run Custom Commands
      if: inputs.custom-command == '' && inputs.custom-commands != ''
      shell: bash
      run: |
        IFS=' ' read -ra COMMANDS <<< "${{ inputs.custom-commands }}"
        for cmd in "${COMMANDS[@]}"; do
          echo "Running: pnpm run $cmd"
          if pnpm run --silent "$cmd" 2>/dev/null; then
            echo "✅ $cmd completed"
          else
            echo "⚠️ $cmd failed or not found"
          fi
        done